// User-Agents reais, com o grupo esperado: 'humano', 'ia' ou 'maquina'.
// Reunidos em 2026-09-29 das documentações oficiais (OpenAI, Anthropic,
// Perplexity, Google, Meta, Mistral, Amazon, DuckDuckGo, Common Crawl, Apple,
// Yandex, Baidu, Bing, Model Context Protocol) e de user-agents.net para
// navegadores e apps. Usado por contagem/teste.mjs.

const CV = '140.0.7339.207';
// [grupo esperado, rótulo, User-Agent]
export const CASOS = [
  // OpenAI (developers.openai.com/api/docs/bots)
  ['ia', 'GPTBot', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; GPTBot/1.4; +https://openai.com/gptbot'],
  ['ia', 'ChatGPT-User', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; ChatGPT-User/1.0; +https://openai.com/bot'],
  ['ia', 'OAI-SearchBot', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36; compatible; OAI-SearchBot/1.4; +https://openai.com/searchbot'],
  ['ia', 'OAI-SearchBot robots', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36; compatible; OAI-SearchBot/1.4; robots.txt; +https://openai.com/searchbot'],
  ['maquina', 'OAI-AdsBot', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; OAI-AdsBot/1.0; +https://openai.com/adsbot'],
  // Anthropic
  ['ia', 'ClaudeBot', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)'],
  ['ia', 'Claude-User', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Claude-User/1.0; +Claude-User@anthropic.com)'],
  ['ia', 'Claude-SearchBot', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Claude-SearchBot/1.0; +Claude-SearchBot@anthropic.com)'],
  ['ia', 'Claude Code WebFetch', 'Claude-User (claude-code/2.1.283; +https://support.anthropic.com/)'],
  // Perplexity
  ['ia', 'PerplexityBot', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)'],
  ['ia', 'Perplexity-User', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Perplexity-User/1.0; +https://perplexity.ai/perplexity-user)'],
  // Google
  ['ia', 'Google-Agent desktop', `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; compatible; Google-Agent; +https://developers.google.com/crawling/docs/crawlers-fetchers/google-agent) Chrome/${CV} Safari/537.36`],
  ['ia', 'Google-Agent mobile', `Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${CV} Mobile Safari/537.36 (compatible; Google-Agent; +https://developers.google.com/crawling/docs/crawlers-fetchers/google-agent)`],
  ['ia', 'Google-GeminiNotebook', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Mobile Safari/537.36 (compatible; Google-GeminiNotebook; +https://developers.google.com/crawling/docs/crawlers-fetchers/google-gemininotebook)'],
  ['ia', 'Google-NotebookLM (token antigo)', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 (compatible; Google-NotebookLM; +https://developers.google.com/search/docs/crawling-indexing/google-user-triggered-fetchers)'],
  ['maquina', 'Google-Read-Aloud', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 (compatible; Google-Read-Aloud; +https://support.google.com/webmasters/answer/1061943)'],
  ['maquina', 'Googlebot smartphone', `Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${CV} Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`],
  ['maquina', 'Googlebot-Image', 'Googlebot-Image/1.0'],
  ['maquina', 'Google-InspectionTool', 'Mozilla/5.0 (compatible; Google-InspectionTool/1.0)'],
  ['maquina', 'GoogleOther desktop', `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GoogleOther) Chrome/${CV} Safari/537.36`],
  ['maquina', 'GoogleOther mobile', `Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${CV} Mobile Safari/537.36 (compatible; GoogleOther)`],
  ['maquina', 'GoogleOther-Image', 'GoogleOther-Image/1.0'],
  ['maquina', 'Storebot-Google', 'Mozilla/5.0 (X11; Linux x86_64; Storebot-Google/1.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'],
  ['maquina', 'AdsBot-Google', 'AdsBot-Google (+http://www.google.com/adsbot.html)'],
  ['maquina', 'Mediapartners-Google', 'Mediapartners-Google'],
  ['maquina', 'APIs-Google', 'APIs-Google (+https://developers.google.com/webmasters/APIs-Google.html)'],
  ['maquina', 'FeedFetcher-Google', 'FeedFetcher-Google; (+http://www.google.com/feedfetcher.html)'],
  ['maquina', 'Google-Site-Verification', 'Mozilla/5.0 (compatible; Google-Site-Verification/1.0)'],
  ['maquina', 'GoogleProducer', 'GoogleProducer; (+https://developers.google.com/search/docs/crawling-indexing/google-producer)'],
  // Meta (developers.facebook.com/docs/sharing/webmasters/web-crawlers)
  ['ia', 'meta-externalagent', 'meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler)'],
  ['ia', 'meta-externalfetcher', 'meta-externalfetcher/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler)'],
  ['ia', 'meta-webindexer', 'meta-webindexer/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler)'],
  ['maquina', 'meta-externalads', 'meta-externalads/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler)'],
  ['maquina', 'facebookexternalhit', 'facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)'],
  ['maquina', 'facebookcatalog', 'facebookcatalog/1.0'],
  // Mistral (docs.mistral.ai/robots)
  ['ia', 'MistralAI-User', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; MistralAI-User/1.0; +https://docs.mistral.ai/robots)'],
  ['ia', 'MistralAI-Index', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; MistralAI-Index/1.0; +https://docs.mistral.ai/robots)'],
  ['ia', 'MistralAI-Training', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; MistralAI-Training/1.0; +https://docs.mistral.ai/robots)'],
  // Amazon (developer.amazon.com/amazonbot)
  ['ia', 'Amazonbot', `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Amazonbot/0.1) Chrome/${CV} Safari/537.36`],
  ['ia', 'Amzn-SearchBot', `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Amzn-SearchBot/0.1) Chrome/${CV} Safari/537.36`],
  ['ia', 'Amzn-User', `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Amzn-User/0.1) Chrome/${CV} Safari/537.36`],
  // DuckDuckGo
  ['maquina', 'DuckDuckBot', 'DuckDuckBot/1.1; (+http://duckduckgo.com/duckduckbot.html)'],
  ['ia', 'DuckAssistBot', 'DuckAssistBot/1.2; (+http://duckduckgo.com/duckassistbot.html)'],
  // Common Crawl
  ['ia', 'CCBot', 'CCBot/2.0 (https://commoncrawl.org/faq/)'],
  // Apple, Yandex, Petal, Baidu, ByteDance, Bing
  ['maquina', 'Applebot', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15 (Applebot/0.1; +http://www.apple.com/go/applebot)'],
  ['maquina', 'YandexBot', 'Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)'],
  ['maquina', 'YandexImages', 'Mozilla/5.0 (compatible; YandexImages/3.0; +http://yandex.com/bots)'],
  ['maquina', 'YandexMetrika', 'Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots)'],
  ['maquina', 'PetalBot', 'Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot)'],
  ['maquina', 'Baiduspider', 'Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)'],
  ['ia', 'Bytespider', 'Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; Bytespider; spider-feedback@bytedance.com)'],
  ['maquina', 'bingbot', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36'],
  // SEO e monitores
  ['maquina', 'UptimeRobot', 'Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)'],
  ['maquina', 'AhrefsBot', 'Mozilla/5.0 (compatible; AhrefsBot/7.0; +http://ahrefs.com/robot/)'],
  ['maquina', 'AhrefsSiteAudit', 'Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/site-audit)'],
  ['maquina', 'SemrushBot', 'Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)'],
  ['maquina', 'Barkrowler', 'Mozilla/5.0 (compatible; Barkrowler/0.9; +https://babbar.tech/crawler)'],
  // Prévias de link
  ['maquina', 'Slackbot', 'Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)'],
  ['maquina', 'Discordbot', 'Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com)'],
  ['maquina', 'Twitterbot', 'Twitterbot/1.0'],
  ['maquina', 'TelegramBot', 'TelegramBot (like TwitterBot)'],
  ['maquina', 'WhatsApp', 'WhatsApp/2.23.20.0 A'],
  ['maquina', 'LinkedInBot', 'LinkedInBot/1.0 (compatible; Mozilla/5.0; Apache-HttpClient +http://www.linkedin.com)'],
  ['maquina', 'iMessage', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4 facebookexternalhit/1.1 Facebot Twitterbot/1.0'],
  ['maquina', 'Bluesky Cardyb', 'Mozilla/5.0 (compatible; Bluesky Cardyb/1.1; +mailto:support@bsky.app)'],
  ['maquina', 'Mastodon', 'http.rb/5.1.1 (Mastodon/4.3.0; +https://mastodon.social/)'],
  ['maquina', 'Teams/Skype preview', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 SkypeUriPreview Preview/0.5 skype-url-preview@microsoft.com'],
  // Agentes e bibliotecas
  ['ia', 'MCP fetch (autônomo)', 'ModelContextProtocol/1.0 (Autonomous; +https://github.com/modelcontextprotocol/servers)'],
  ['ia', 'MCP fetch (usuário)', 'ModelContextProtocol/1.0 (User-Specified; +https://github.com/modelcontextprotocol/servers)'],
  ['maquina', 'Node fetch (Node 20+)', 'node'],
  ['maquina', 'Node fetch (Node 18)', 'undici'],
  ['maquina', 'Deno', 'Deno/2.1.4'],
  ['maquina', 'Bun', 'Bun/1.1.38'],
  ['maquina', 'Java HttpClient', 'Java-http-client/21.0.4'],
  ['maquina', 'Ruby Net::HTTP', 'Ruby'],
  ['maquina', 'Guzzle', 'GuzzleHttp/7'],
  ['maquina', 'Postman', 'PostmanRuntime/7.42.0'],
  ['maquina', 'python-requests', 'python-requests/2.32.3'],
  ['maquina', 'httpx', 'python-httpx/0.28.1'],
  // Humanos
  ['humano', 'Chrome Windows', `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36`],
  ['humano', 'Chrome Android', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Mobile Safari/537.36'],
  ['humano', 'Chrome iOS', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/140.0.7339.122 Mobile/15E148 Safari/604.1'],
  ['humano', 'Safari iOS', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1'],
  ['humano', 'Safari iOS 26', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.0 Mobile/15E148 Safari/604.1'],
  ['humano', 'Samsung Internet', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/28.0 Chrome/130.0.0.0 Mobile Safari/537.36'],
  ['humano', 'Firefox Android', 'Mozilla/5.0 (Android 15; Mobile; rv:143.0) Gecko/143.0 Firefox/143.0'],
  ['humano', 'Instagram iOS', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 395.0.0.25.83 (iPhone15,3; iOS 18_6; pt_BR; pt; scale=3.00; 1290x2796; 791234567)'],
  ['humano', 'Instagram Android', 'Mozilla/5.0 (Linux; Android 14; SM-A546E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/140.0.7339.51 Mobile Safari/537.36 Instagram 395.0.0.25.83 Android (34/14; 450dpi; 1080x2340; samsung; SM-A546E; a54x; s5e8835; pt_BR; 791234567)'],
  ['humano', 'Facebook iOS', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBAV/526.0.0.43.109;FBBV/771234567;FBDV/iPhone15,3;FBMD/iPhone;FBSN/iOS;FBSV/18.6;FBSS/3;FBID/phone;FBLC/pt_BR;FBOP/5;FBRV/0]'],
  ['humano', 'Facebook Android', 'Mozilla/5.0 (Linux; Android 14; SM-A546E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/140.0.7339.51 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/526.0.0.43.109;IABMV/1;]'],
  ['humano', 'TikTok Android', 'Mozilla/5.0 (Linux; Android 14; SM-A546E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/140.0.7339.51 Mobile Safari/537.36 musical_ly_2024107030 JsSdk/1.0 NetType/WIFI Channel/googleplay AppName/musical_ly app_version/41.7.3 ByteLocale/pt-BR ByteFullLocale/pt-BR Region/BR AppId/1233 Spark/1.7.4.2-bugfix AppVersion/41.7.3 BytedanceWebview/d8a21c6'],
  ['humano', 'TikTok iOS', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 musical_ly_41.7.0 JsSdk/2.0 NetType/WIFI Channel/App Store ByteLocale/pt Region/BR RevealType/Dialog isDarkMode/0 WKWebView/1 BytedanceWebview/d8a21c6 FalconTag/'],
  ['humano', 'Telegram Android', 'Mozilla/5.0 (Linux; Android 14; SM-A546E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/140.0.7339.51 Mobile Safari/537.36 Telegram-Android/12.0.1 (Samsung SM-A546E; Android 14; SDK 34; HIGH)'],
  ['humano', 'WebView em Cubot (user-agents.net)', 'Mozilla/5.0 (Linux; Android 7.0; CUBOT R9 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36'],
  ['humano', 'Opera em Cubot (user-agents.net)', 'Mozilla/5.0 (Linux; Android 6.0; CUBOT MAX Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36 OPR/43.0.2246.121183'],
  ['humano', 'DuckDuckGo iOS', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 DuckDuckGo/7 Safari/605.1.15'],
  ['humano', 'Google app iOS', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/385.0.797924893 Mobile/15E148 Safari/604.1'],
  ['humano', 'Edge', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0'],
  ['humano', 'LINE', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Safari Line/15.12.0'],
  ['humano', 'Snapchat', 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Snapchat/13.50.0.47 (like Safari/8621.1.15.10.7, panda)'],
  ['humano', 'Opera Mini', 'Opera/9.80 (Android; Opera Mini/88.0.2254/191.371; U; sw) Presto/2.12.423 Version/12.16'],
  ['humano', 'Internet Explorer 11', 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko'],
  ['humano', 'Internet Explorer 10', 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)'],
  // Nomes novos de IA (2026-10-03): User-Agents observados, de knownagents.com
  ['ia', "AgentDataBot", "AgentDataBot/1.0 (+https://agentdata.run/bot)"],
  ['ia', "AI2Bot", "Mozilla/5.0 (compatible) AI2Bot (+https://www.allenai.org/crawler)"],
  ['ia', "Ai2Bot-Dolma", "AI2Bot-Dolma (+https://www.allenai.org/crawler)"],
  ['ia', "AIWebIndex", "AIWebIndex/2.0 (+https://lyrenth.com/bot; AI-readable web index)"],
  ['ia', "Amazonbot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot) Chrome/119.0.6045.214 Safari/537.36"],
  ['ia', "Amzn-SearchBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Amzn-SearchBot/0.1) Chrome/119.0.6045.214 Safari/537.36"],
  ['ia', "Anomura", "Anomura/1.2 (+https://www.direqt-search.com)"],
  ['ia', "Aranet-SearchBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Aranet-SearchBot/1.0; +https://aranet.ai/bot) Chrome/131.0.0.0 Safari/537.36"],
  ['ia', "AzureAI-SearchBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; AzureAI-SearchBot/1.0;"],
  ['ia', "Channel3Bot", "Mozilla/5.0 (compatible; Channel3Bot/1.0; +https://trychannel3.com/channel3bot)"],
  ['ia', "ChatGLM-Spider", "Mozilla/5.0 (compatible; ChatGLM-Spider/1.0; +https://zhipuai.cn/)"],
  ['ia', "Claude-Code", "Claude-User (claude-code/2.1.281; +https://support.anthropic.com/)"],
  ['ia', "Claude-SearchBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Claude-SearchBot/1.0; +searchbot@anthropic.com)"],
  ['ia', "Claude-User", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Claude-User/1.0; +claude-user@anthropic.com)"],
  ['ia', "Claude-Web", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Claude-Web/1.0; +https://www.anthropic.com)"],
  ['ia', "CloudflareBrowserRenderingCrawler", "CloudflareBrowserRenderingCrawler/1.0"],
  ['ia', "cohere-ai", "Mozilla/5.0 (compatible; cohere-ai; +https://cohere.com/crawler)"],
  ['ia', "Cotoyogi", "Mozilla/5.0 (compatible; Cotoyogi/4.0; +https://ds.rois.ac.jp/center8/crawler/)"],
  ['ia', "DeepSeekBot", "Mozilla/5.0 (compatible; DeepSeekBot/1.0; +https://www.deepseek.com/)"],
  ['ia', "Diffbot", "Diffbot/1.0"],
  ['ia', "ExaBot", "ExaBot/1.0 (+https://exa.ai/webmaster)"],
  ['ia', "ExaSearchBot", "Mozilla/5.0 (compatible; ExaSearchBot/1.0; +https://crawler.exa.ai/)"],
  ['ia', "FacebookBot", "Mozilla/5.0 (compatible; FacebookBot/1.0; +https://developers.facebook.com/docs/sharing/webmasters/facebookbot/)"],
  ['ia', "Gemini-Deep-Research", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Gemini-Deep-Research; +https://gemini.google/overview/deep-research/) Chrome/135.0.0.0 Safari/537.36"],
  ['ia', "Google-CloudVertexBot", "Mozilla/5.0 (compatible; Google-CloudVertexBot; +https://cloud.google.com/vertex-ai-bot)"],
  ['ia', "Google-Gemini-CLI", "Mozilla/5.0 (compatible; Google-Gemini-CLI/1.0; +https://github.com/google-gemini/gemini-cli)"],
  ['ia', "GoogleAgent-Mariner", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; compatible; GoogleAgent-Mariner) Chrome/149.0.7827.196 Safari/537.36"],
  ['ia', "GPTBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.4; +https://openai.com/gptbot)"],
  ['ia', "HenkBot", "Mozilla/5.0 (compatible; HenkBot/1.0; +https://valyu.ai/crawler)"],
  ['ia', "iAskBot", "Mozilla/5.0 AppleWebKit/605.1.15 (KHTML, like Gecko; compatible; iAskBot/1.0; +https://iask.ai/) Chrome/124.0.6367.171 Safari/605.1.15"],
  ['ia', "iaskspider", "Mozilla/5.0 (compatible; iaskspider/1.0; MSIE 6.0)"],
  ['ia', "ICC-Crawler", "ICC-Crawler/3.0 (Mozilla-compatible; ; https://ucri.nict.go.jp/en/icccrawler.html)"],
  ['ia', "ImagesiftBot", "Mozilla/5.0 (compatible; ImagesiftBot; +imagesift.com)"],
  ['ia', "kagi-fetcher", "kagi-fetcher/1.0"],
  ['ia', "KeenableBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; KeenableBot/1.0; +https://keenable.ai/)"],
  ['ia', "Kimi-Agent", "Mozilla/5.0 Kimi-Agent/2.5"],
  ['ia', "Kimi-SearchBot", "Mozilla/5.0 (compatible; Kimi-SearchBot/1.0; +https://kimi.ai/)"],
  ['ia', "Kimi-User", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; Kimi-User/1.0; +https://www.kimi.com/policies/kimi-crawlers"],
  ['ia', "KimiBot", "Mozilla/5.0 (compatible; KimiBot/1.0; +https://kimi.ai/)"],
  ['ia', "KlaviyoAIBot", "KlaviyoAIBot/1.0 (+https://help.klaviyo.com/hc/en-us/articles/40496146232219)"],
  ['ia', "LinkupBot", "LinkupBot/1.0 (LinkupBot for web indexing; https://linkup.so/bot; bot@linkup.so)"],
  ['ia', "Manus-User", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36; Manus-User/1.0"],
  ['ia', "meta-externalagent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"],
  ['ia', "meta-externalfetcher", "Meta-ExternalFetcher/1.0"],
  ['ia', "meta-webindexer", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 (compatible; meta-webindexer/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler))"],
  ['ia', "MistralAI-Index", "Mozilla/5.0 (compatible; MistralAI-Index/1.0; +https://docs.mistral.ai/robots)"],
  ['ia', "MistralAI-User", "Mozilla/5.0 (compatible; MistralAI-User/1.0; +https://mistral.ai/)"],
  ['ia', "PanguBot", "Mozilla/5.0 (compatible; PanguBot/1.0; +https://www.huaweicloud.com/)"],
  ['ia', "Perplexity-User", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Perplexity-User/1.0; +https://perplexity.ai/perplexitybot)"],
  ['ia', "Poggio-Citations", "Poggio-Citations 1.0 (+https://docs.poggio.io/api/robots)"],
  ['ia', "qodercli", "qodercli/1.1.62 (+https://qoder.com)"],
  ['ia', "Querit-SearchBot", "Mozilla/5.0 (compatible; Querit-SearchBot/1.0; +https://www.querit.ai)"],
  ['ia', "QueritBot", "Mozilla/5.0 (compatible; QueritBot/1.0; +https://www.querit.ai/bot)"],
  ['ia', "QwenBot", "Mozilla/5.0 (compatible; Qwenbot/1.0; +https://qwen.alibaba.com/)"],
  ['ia', "Reflectionbot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Reflectionbot/1.0; +https://reflection.ai/bot) Chrome/151.0.0.0 Safari/537.36"],
  ['ia', "SBIntuitionsBot", "Mozilla/5.0 (compatible; SBIntuitionsBot/0.1;+https://www.sbintuitions.co.jp/bot/)"],
  ['ia', "Shap-User", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; Shap-User/0.1.0"],
  ['ia', "ShapBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko); compatible; ShapBot/0.1.0"],
  ['ia', "TavilyBot", "Mozilla/5.0 (compatible; TavilyBot/1.0)"],
  ['ia', "TikTokSpider", "Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; TikTokSpider; ttspider-feedback@tiktok.com)"],
  ['ia', "Timpibot", "Mozilla/5.0 (compatible; Timpibot/1.0; +http://www.timpi.io)"],
  ['ia', "UseAI", "Mozilla/5.0 (compatible; UseAI/1.0; +https://agents.urls.use.ai) AppleWebKit/537.36"],
  ['ia', "VelenPublicWebCrawler", "Mozilla/5.0 (compatible; VelenPublicWebCrawler/1.0; +https://velen.io)"],
  ['ia', "YouBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; YouBot/1.0; +https://docs.you.com/youbot; env:prod) Chrome/142.0.0.0 Safari/537.36"],
  ['ia', "ZanistaBot", "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ZanistaBot/1.0; +https://zanista.ai/crawler-info) Chrome/W.X.Y.Z Safari/537.36"],
  // Navegadores de texto, usados por pessoas (inclusive com leitor de tela e
  // linha braille): exemplos das documentações de cada um.
  ['humano', "Lynx", "Lynx/2.9.3 libwww-FM/2.14 SSL-MM/1.4.1 GNUTLS/3.8.9"],
  ['humano', "w3m", "w3m/0.5.3+git20230121"],
  ['humano', "emacs-w3m", "Emacs-w3m/1.4.632 w3m/0.5.3+git20230121"],
  ['humano', "ELinks", "ELinks/0.18.0 (textmode; Linux 6.12.48+deb13-amd64 x86_64; 80x24-2)"],
  ['humano', "Links", "Links (2.29; Linux 6.12.48+deb13-amd64 x86_64; GNU C 14.2; text)"],
  ['humano', "eww (Emacs)", "URL/Emacs Emacs/30.1 (X11; x86_64-pc-linux-gnu)"],
  ['humano', "edbrowse", "edbrowse/3.8.10"],
];
